### ISSUE TITLE
hkg.plus redirect左去https://lihk-forum.firebaseapp.com/

### ISSUE THREAD

**Issue by Saren-Arterius** [colloquet/lihkg-web#2]
大家都知hkg.plus個domain臭左。希望可以check referer，係頁頂澄一澄清呢個project同hkg.plus冇關。

**Comment by colloquet** [comment]
收到，唔該巴打通知！

**Comment by Saren-Arterius** [comment]
入https://lihk-forum.firebaseapp.com/唔會出notice，
直接入https://lihk-forum.firebaseapp.com/category/1先會

**Comment by colloquet** [comment]
巴打有心！真係好好奇hkg.plus個owner係乜水同搞邊科，我見佢好似有寫埋API，最後尾又冇料到。

**Comment by Saren-Arterius** [comment]
我都想知:joy::joy:
個網鬼鬼地，幾個鐘之前仲係redirect去lihkg.na.cx，但lihkg.na.cx幫佢redirect去hkgolden.com:joy::joy:

**Comment by nodegin** [comment]
你redirect去 hkgolden.com 啦

**Comment by colloquet** [comment]
搞左一排都搞唔掂firebase個redirect，最後都係用JS redirect算。😂
