### ISSUE TITLE
bookmark功能

### ISSUE THREAD

**Issue by psdp** [colloquet/lihkg-web#5]
期望可加入bookmark功能，因有時想再睇番舊post已經搵唔返出嚟。thx！

**Comment by colloquet** [comment]
Hi @psdp ,

加入bookmark功能係可以但只係會儲存係browser既localStorage，因為呢個只係一個client side reader，唔會有登入或同步功能。

如果你想做到幾部裝置同步bookmark既我建議用返官方app既留名功能。

Colloque

**Comment by colloquet** [comment]
@psdp ok明白了，我會開始睇下點搞😄

**Comment by psdp** [comment]
@colloquet thanks a lot! :+1:

**Comment by colloquet** [comment]
@psdp 唔好意思搞左咁耐，比我預期中複雜，所以拖左一排。不過已經啱啱 deploy 咗，可以試下睇下有冇 bug 😄

**Comment by psdp** [comment]
@colloquet 試左bookmark功能，好有用呀！多謝你 :smiley:

**Comment by colloquet** [comment]
咁就好👍
